version: '3.7'

services:
  # PostgreSQL
  pg-db:
    container_name: pg-db
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - db-data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - node-postgres-network

  # PgAdmin4
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.29
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    depends_on:
      - pg-db
    networks:
      - node-postgres-network

  # API
  test-api:
    container_name: api
    build: ./
    image: express-api
    volumes:
      - ./:/usr/src/test-project/
      - /usr/src/test-project/node_modules/
    ports:
      - 3000:3000
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      PORT: ${PORT:-3000}
    depends_on:
      - pg-db
    networks:
      - node-postgres-network

networks: 
  node-postgres-network:
    driver: bridge

volumes:
    db-data:
    pgadmin:
